[package]
name = "mqtt_client"
version = "0.1.0"
edition="2024"

[dependencies]
rumqttc = "0.25.0"
tokio = { version = "1.48.0", features = ["full"] }
openai-api-rs = "6.0.10"

[dev-dependencies]
tokio = { version = "1.48.0", features = ["full"] }
openai-api-rs = "6.0.10"
